code = "baobabi"
name = "baobabi"
version = 2

author = "Krišjānis Petručeņa"
tags = ["brute-force","math","number-theory"]

type = "batch"
time_lim= 1.0
mem_lim = 256

[[subtasks]]
name = "A=1,B<=10^3"
score = 12

[[subtasks]]
name = "B<=10^5"
score = 14

[[subtasks]]
name = "(B-A)<=10^5"
score = 16

[[subtasks]]
name = "B<=10^9"
score = 18

[[subtasks]]
name = "B<=10^11"
score = 20

[[subtasks]]
name = "MAX"
score = 20
